# Generated by Django 3.0.3 on 2020-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200304_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sprite',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
