# Generated by Django 3.0.3 on 2020-03-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200304_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='item',
        ),
    ]
