# Generated by Django 3.0.3 on 2020-03-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_remove_player_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adventure.Item'),
        ),
        migrations.AddField(
            model_name='player',
            name='sprite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
