# Generated by Django 3.0.3 on 2020-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_auto_20200304_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_path',
            field=models.BooleanField(default=True),
        ),
    ]
