# Generated by Django 3.0.3 on 2020-03-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_room_is_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.IntegerField(null=True),
        ),
    ]
